[workspace]
members = [
    "actix-surreal-starter",
    "actix-surreal-starter-macros",
    "proc_macros",
    "server",
    "web_client", "zola-watcher",
]
resolver = "2"

[profile.release]
opt-level = 3
codegen-units = 1
