[package]
name = "proc_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.40"
syn = { version = "1.0.109", features = ["full"] }
heck = "0.5.0"
proc_macro_utils = { path = "proc_macro_utils" }
proc-macro2 = "1.0.95"

[lib]
proc-macro = true