[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.10.2"
surrealdb = "2.2.1"
actix-surreal-starter = { path = "../actix-surreal-starter" }
chrono = "0.4.40"
entities = { path = "entities", features = ["server"] }